config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  controller :sessions do
    get 'login', action: :new
    post 'login', action: :create
    delete 'logout', action: :destroy
  end

  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

app/views/layouts/_header.html.erb
<section class="section">
  <nav class="navbar has-background-grey-darker is-fixed-top has-shadow is-spaced" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item">
        <%= image_tag('logo.png') %>
      </a>
    </div>
    <div class="navbar-menu">
      <div class="navbar-end">
        <%= form_tag store_index_path, class: 'select is-small' do %>
          <%= select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: 'this.form.submit()' %>
          <%= submit_tag 'submit', id: "submit_locale_change", class: "button is-small" %>
        <% end %>
      </div>
    </div>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
    <%= javascript_pack_tag 'locale_switcher', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <section class="section">
      <div class="columns">
        <div class="column is-4-tablet is-4-desktop is-3-widescreen">
          <nav class="menu">
            <p id="time" class="menu-label has-text-weight-light is-family-code">
              <%= Time.now.strftime("%^a, %^b %d %Y") %> | <%= Time.now.strftime("%R") %>
            </p>
            <hr class="hr">
            <% if @cart %>
              <div id="cart" class="notification cart">
                <%= render_if @cart && @cart.line_items.any?, @cart %>
              </div>
              <hr class="hr">
            <% end %>
            <ul class="menu-list">
              <li>
                <a href="/home" class="has-text-dark"><%= t('.home') %></a>
              </li>
              <li>
                <a href="/questions" class="has-text-dark"><%= t('.questions') %></a>
              </li>
              <li>
                <a href="/news" class="has-text-dark"><%= t('.news') %></a>
              </li>
              <li>
                <a href="/contact" class="has-text-dark"><%= t('.contact') %></a>
              </li>
              <% if session[:user_id] %>
                <hr>
                <li><%= link_to 'ORDERS', orders_path, class:"has-text-dark"%></li>
                <li><%= link_to 'PRODUCTS', products_path, class:"has-text-dark" %></li>
                <li><%= link_to 'USERS', users_path, class:"has-text-dark" %></li>
                <li><%= link_to 'LOGOUT', logout_path, method: :delete, class: 'has-text-dark is-light' %></li>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="column">
          <main class='<%= controller.controller_name %>'>
            <div class="container">
              <%= yield %>
            </div>
          </main>
        </div>
      </div>
    </section>
  </body>
</html>